pipeline_steps:
  - class: LoadDataframeFromPath
    kwargs:
      file_type: "csv"
      filepath_or_buffer: "archive/online_retail.csv"
  - class: InitializeDatabaseConnection
  - class: SaveDataframeToDatabase
    kwargs:
      schema_name: "retail_schema"
      table_name: "raw_online_retail"
  - class: RemoveNulls
  - class: RemoveDuplicates
  - class: ValidateData
  - class: ConvertStrToDatetime
    kwargs:
      date_column: "InvoiceDate"
  - class: ConvertFloatToStr
    kwargs:
      str_column: "CustomerID"
  - class: CreateNewTable
    kwargs:
      schema_name: "retail_schema"
      table_name: "products"
      table_columns: ['StockCode', 'Description', 'UnitPrice']
      distinct: 1
  - class: CreateNewTable
    kwargs:
      schema_name: "retail_schema"
      table_name: "customers"
      table_columns: ["CustomerID", "Country"]
      distinct: 1
  - class: CreateNewTable
    kwargs:
      schema_name: "retail_schema"
      table_name: "sales_transactions"
      table_columns: ['InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'CustomerID']
      distinct: 0
  - class: ExecuteQuery
    kwargs:
      query: "
              ALTER TABLE retail_schema.products
              ADD product_id SERIAL,
              ADD PRIMARY KEY (product_id);
             "
  - class: ExecuteQuery
    kwargs:
      query: "
              ALTER TABLE retail_schema.customers
              ADD customer_id SERIAL,
              ADD PRIMARY KEY (customer_id);
             "
  - class: ExecuteQuery
    kwargs:
      query: "
              ALTER TABLE retail_schema.sales_transactions
              ADD order_id SERIAL,
              ADD PRIMARY KEY (order_id);
             "
# This part will be executed after contacting the client and discussing which stock code to keep
#  - class: ExecuteQuery
#    kwargs:
#      query: "
#              ALTER TABLE retail_schema.sales_transactions
#              ADD CONSTRAINT fk_stock_code
#              FOREIGN KEY ('StockCode')
#              REFERENCES retail_schema.products ('StockCode');
#             "
#  - class: ExecuteQuery
#    kwargs:
#      query: "
#              CREATE INDEX IF NOT EXISTS idx_stock_code ON table_name ('retail_schema.sales_transactions');
#             "
  - class: CloseDatabaseConnection